from __future__ import annotations

from pathlib import Path
from string import Template

import pandas as pd


def build_report(results, output: str | Path = "report.html") -> Path:
    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    html = Template(_HTML_TEMPLATE).substitute(
        summary=_frame_to_html(results.summary),
        regime_summary=_frame_to_html(results.regime_summary),
        simulations=_frame_to_html(results.simulations.head(20)),
        crisis_replay=_frame_to_html(results.crisis_replay),
        metadata=_metadata_table(results.metadata),
    )
    output_path.write_text(html, encoding="utf-8")
    return output_path


def _frame_to_html(frame: pd.DataFrame) -> str:
    if frame.empty:
        return "<p>No rows.</p>"
    display = frame.copy()
    for column in display.columns:
        if pd.api.types.is_float_dtype(display[column]):
            display[column] = display[column].map(lambda value: "" if pd.isna(value) else f"{value:.6f}")
    return display.to_html(index=False, escape=True, classes="data-table")


def _metadata_table(metadata: dict[str, object]) -> str:
    rows = "".join(f"<tr><th>{key}</th><td>{value}</td></tr>" for key, value in metadata.items())
    return f"<table class=\"data-table\">{rows}</table>"


_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Strategy Regime Stress Lab Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 32px; color: #1d2433; }
    h1, h2 { margin-bottom: 8px; }
    .notice { border: 1px solid #b8c0cc; background: #f7f9fc; padding: 12px 14px; border-radius: 6px; }
    .data-table { border-collapse: collapse; width: 100%; margin: 16px 0 28px; font-size: 13px; }
    .data-table th, .data-table td { border: 1px solid #d8dee8; padding: 6px 8px; text-align: right; }
    .data-table th { background: #eef2f7; }
    .data-table th:first-child, .data-table td:first-child { text-align: left; }
  </style>
</head>
<body>
  <h1>Strategy Regime Stress Lab</h1>
  <p class="notice">
    This report is generated by a research and risk analysis tool. It summarizes historical and simulated strategy
    return behavior across market regimes. It is not investment advice and does not provide security recommendations.
  </p>

  <h2>Run Metadata</h2>
  $metadata

  <h2>Strategy Summary</h2>
  $summary

  <h2>Regime-wise Performance</h2>
  $regime_summary

  <h2>Historical Stress Replay</h2>
  $crisis_replay

  <h2>Simulation Sample</h2>
  $simulations
</body>
</html>
"""
